"use client";

import { motion } from "framer-motion";
import ScreenshotSlot from "./ScreenshotSlot";

const features = [
  { title: "On-Device AI Assistant", description: "Nomadical includes a fully offline AI chat assistant powered by Gemma 4 2B, running entirely on your Android device with GPU inference and a CPU fallback for broader compatibility. You can ask survival questions, get step-by-step guidance, and receive contextual answers without ever sending data to a remote server. Because all processing happens locally, there are no subscription fees, no API costs, and no privacy trade-offs. The AI model is downloaded once during initial setup and then operates independently of any internet connection. This makes it reliable in remote wilderness areas, emergency situations, or any environment where connectivity is unavailable.", useCase: "A hiker becomes stranded after a trail washout and loses cell service. They open Nomadical and ask the AI assistant how to build an emergency debris shelter for overnight temperatures near freezing. The assistant provides detailed, step-by-step guidance entirely on-device, with no signal required.", howItWorks: ["Step 1: Download the Gemma 4 2B AI model during initial app setup while connected to Wi-Fi.", "Step 2: Open the AI chat screen and type or ask your survival question in natural language.", "Step 3: The model processes your query entirely on-device and returns a detailed response — no internet connection needed."], screenshotLabel: "Screenshot: The AI chat interface showing a user question about shelter building and a detailed on-device AI response", screenshotHint: "Recommended: portrait, full screen showing chat bubbles and input field", color: "#263e0f" },
  { title: "Document RAG — Chat With Your Own Files", description: "Nomadical's on-device Retrieval-Augmented Generation (RAG) system lets you import your own PDF, TXT, and Markdown documents and then chat with them using the AI assistant. The app indexes your uploaded files locally and retrieves relevant passages to ground AI responses in your specific documents. This means you can bring your own field manuals, medical references, or personal notes and query them intelligently without any cloud processing. A cross-library search feature lets you query across all uploaded documents simultaneously. All indexing, retrieval, and inference happen on-device, keeping your personal documents completely private.", useCase: "A wilderness medicine instructor uploads their personal field reference manual as a PDF before leading a remote expedition. During the trip, they chat with the document to quickly locate specific wound care protocols, with the AI surfacing the exact relevant passages from their own manual — offline and instantly.", howItWorks: ["Step 1: Import a PDF, TXT, or Markdown file from your device into the Nomadical document library.", "Step 2: Open the document chat interface and type a question referencing the content of your file.", "Step 3: The on-device RAG system retrieves relevant passages and the AI generates a grounded answer based on your document's content."], screenshotLabel: "Screenshot: The document chat screen showing an imported PDF and an AI response citing content from the uploaded file", screenshotHint: "Recommended: portrait, showing document title at top and chat conversation below", color: "#6366f1" },
  { title: "Survival Article Library", description: "Nomadical includes a curated library of over 1,000 survival articles organized across 22 categories, including First Aid, Navigation, Knots, Foraging, Shelter, Fire, and Water. All articles are stored on-device and accessible without any internet connection. Full-text search powered by BM25 ranking lets you find relevant articles quickly even across the entire library. You can bookmark articles for fast access and flag articles to mark them for review or follow-up. The breadth of categories ensures coverage across the full spectrum of wilderness and emergency preparedness topics.", useCase: "A backcountry camper wants to refresh their knowledge on water purification methods before a multi-day trip into an area without potable water sources. They search the library for 'water purification' and instantly find ranked, relevant articles covering boiling, filtration, and chemical treatment — all readable offline.", howItWorks: ["Step 1: Open the article library and browse by category or use the full-text search bar to enter keywords.", "Step 2: BM25 ranking surfaces the most relevant articles from the 1,000+ entry library.", "Step 3: Read the article offline, then bookmark or flag it for future quick reference."], screenshotLabel: "Screenshot: The article library screen showing category tiles and a search results list with BM25-ranked articles", screenshotHint: "Recommended: portrait, showing category grid at top and search results list below", color: "#8b5cf6" },
  { title: "AI Scanner — Plant, Animal & Object Identification", description: "The AI Scanner uses Nomadical's on-device vision model to identify plants, and objects through your device's camera. Point the camera at a subject and the vision model analyzes the image locally, returning identification results without sending any image data to external servers. This feature is designed to assist with foraging decisions, wildlife awareness, and field identification tasks in environments where internet access is unavailable. Because the model runs on-device, identification results are available even in areas with no cellular or Wi-Fi signal. As with all AI features, results should be verified against authoritative sources before acting on them.", useCase: "A forager spots an unfamiliar mushroom on a trail and wants a preliminary identification before deciding whether to harvest it. They open the AI Scanner, point their camera at the mushroom, and receive an on-device identification result to help inform their decision — with no cell signal required.", howItWorks: ["Step 1: Open the AI Scanner from the app and point your device camera at the plant, animal, or object you want to identify.", "Step 2: The on-device vision model analyzes the camera image locally.", "Step 3: The app returns an identification result with relevant information, entirely offline."], screenshotLabel: "Screenshot: The AI Scanner screen showing a camera viewfinder with an on-device identification result displayed below", screenshotHint: "Recommended: portrait, camera viewfinder occupying upper two-thirds with result card below", color: "#06b6d4" },
  { title: "Automatic On-Device OCR for Scanned PDFs", description: "When you import a scanned PDF that contains image-based text rather than selectable text, Nomadical automatically runs on-device Optical Character Recognition (OCR) using Google ML Kit to extract the text content. This means physical documents you have photographed or scanned — such as printed field guides, handwritten notes converted to PDF, or legacy reference materials — become fully searchable and usable within the document RAG system. The OCR process happens entirely on your device without uploading your documents anywhere. Once processed, the extracted text is available for AI-powered chat and cross-library search. This removes the barrier of needing digitally-native documents to benefit from the AI assistant.", useCase: "A search and rescue volunteer has a printed regional plant identification guide that they scanned to PDF on their home printer. They import the scanned PDF into Nomadical, and the app automatically runs OCR to extract the text, making the entire guide searchable and available for AI-assisted queries during field operations.", howItWorks: ["Step 1: Import a scanned or image-based PDF into the Nomadical document library.", "Step 2: The app detects that the PDF lacks selectable text and automatically triggers on-device OCR via Google ML Kit.", "Step 3: The extracted text is indexed locally, making the document available for AI chat and cross-library search."], screenshotLabel: "Screenshot: The document import screen showing an OCR processing indicator on a scanned PDF file", screenshotHint: "Recommended: portrait, document list with a processing status badge on the scanned file entry", color: "#10b981" },
  { title: "Digital Compass with True North Correction", description: "Nomadical includes a digital compass that provides bearing readings with true north correction and magnetic declination adjustment. Magnetic declination — the difference between magnetic north and true north — varies by geographic location, and the app accounts for this to give you accurate directional readings. This makes the compass useful for navigation tasks that require true north orientation, such as map reading and route planning. The compass operates using your device's built-in magnetometer and does not require an internet connection. It is designed as a practical field navigation tool for use in remote environments.", useCase: "A wilderness navigator is using a topographic map that references true north and needs their compass to match. They open the Nomadical compass, which applies magnetic declination correction for their location, giving them a true north bearing that aligns with their map for accurate route planning.", howItWorks: ["Step 1: Open the Digital Compass screen within Nomadical.", "Step 2: The app reads your device's magnetometer and applies magnetic declination correction for true north alignment.", "Step 3: A real-time compass bearing is displayed, corrected for true north, ready for use with maps or navigation tasks."], screenshotLabel: "Screenshot: The digital compass screen showing a compass rose, current bearing, and true north correction indicator", screenshotHint: "Recommended: portrait, compass rose centered with bearing readout and declination value displayed", color: "#f59e0b" },
  { title: "Field Journal with GPS Tagging and Photo Capture", description: "The Field Journal lets you create written entries directly within Nomadical, with each entry optionally tagged with your current GPS coordinates and accompanied by photos captured in-app. This creates a location-aware log of observations, findings, campsites, water sources, or any field notes you want to record. GPS tagging works using your device's location hardware and does not require internet connectivity. Photos are stored locally on your device alongside the journal entry. The journal is designed for use during active field operations where documenting your environment and movements is valuable.", useCase: "A wilderness survival instructor is scouting a new training area and wants to document water source locations, notable landmarks, and plant observations for future reference. They use the Field Journal to create GPS-tagged entries with photos at each point of interest, building an offline record they can reference on future visits.", howItWorks: ["Step 1: Open the Field Journal and create a new entry by tapping the add button.", "Step 2: Write your notes, optionally capture a photo using the in-app camera, and tag the entry with your current GPS coordinates.", "Step 3: The entry is saved locally with its location data and photo, accessible offline at any time."], screenshotLabel: "Screenshot: The Field Journal entry screen showing a text note, an attached photo thumbnail, and GPS coordinates", screenshotHint: "Recommended: portrait, entry form with text area, photo thumbnail, and GPS coordinate display", color: "#263e0f" },
  { title: "Emergency Checklists", description: "Nomadical includes an emergency checklist system with pre-built checklists covering common survival and preparedness scenarios, as well as the ability to create fully custom checklists. Pre-built options provide a ready-made starting point for standard emergency preparedness tasks, while custom checklists let you tailor lists to your specific activities, gear, or situations. Checklists are stored on-device and accessible without internet. This feature is designed to reduce cognitive load in high-stress situations by giving you a structured, step-by-step reference. Items can be checked off as they are completed.", useCase: "An outdoor guide prepares a custom pre-trip safety checklist specific to their kayaking expeditions, covering gear checks, communication devices, and emergency contacts. Before each trip they run through the checklist in Nomadical to ensure nothing is missed, even when working from a remote launch point without cell service.", howItWorks: ["Step 1: Open the Checklists section and either select a pre-built emergency checklist or tap to create a custom one.", "Step 2: Add, edit, or reorder checklist items to match your specific needs.", "Step 3: Work through the checklist in the field, tapping items to mark them as complete."], screenshotLabel: "Screenshot: The checklists screen showing a pre-built emergency checklist with checked and unchecked items", screenshotHint: "Recommended: portrait, checklist with item rows showing checkboxes and a mix of completed and pending items", color: "#6366f1" },
  { title: "SOS Mode with Morse Code Signaling", description: "Nomadical's SOS mode enables emergency distress signaling using the international SOS Morse code pattern transmitted through three simultaneous output channels: the device torch (flashlight), the phone screen, and device vibration. This multi-channel approach maximizes the chance of the signal being detected by rescuers in low-visibility or noisy environments. The feature requires no network connection and works entirely using the device's hardware. SOS mode is designed for genuine emergency situations where attracting the attention of rescuers is critical. It can be activated quickly from within the app.", useCase: "A solo hiker suffers an ankle injury after dark in a remote area with no cell signal. Unable to walk out, they activate Nomadical's SOS mode, which begins flashing the torch, pulsing the screen, and vibrating in the SOS Morse code pattern to signal their position to a search and rescue team scanning the area.", howItWorks: ["Step 1: Navigate to SOS mode within the Nomadical app and activate it.", "Step 2: The app simultaneously triggers the device torch, screen flash, and vibration in the SOS Morse code pattern.", "Step 3: The signaling continues, drawing attention from rescuers, until you manually deactivate it."], screenshotLabel: "Screenshot: The SOS mode screen showing the active signaling state with torch, screen, and vibration indicators highlighted", screenshotHint: "Recommended: portrait, full-screen SOS activation view with status indicators for each signaling channel", color: "#8b5cf6" },
  { title: "Medical ID", description: "The Medical ID feature lets you store critical personal health information directly within Nomadical, including blood type, allergies, current medications, and emergency contacts. This information is stored locally on your device and is accessible offline at any time. In an emergency, having this information readily available can assist first responders or fellow travelers in providing appropriate care. The Medical ID is designed to be a quick-access reference for situations where you may be unable to communicate your own medical history. All data remains on your device and is never transmitted externally.", useCase: "A diabetic backpacker stores their insulin type, dosage, known allergies, and their doctor's contact information in Nomadical's Medical ID before a solo trip. If they become incapacitated, a fellow hiker or first responder can open the app and immediately access the critical medical information needed to assist them.", howItWorks: ["Step 1: Open the Medical ID section and enter your blood type, allergies, medications, and emergency contact details.", "Step 2: The information is saved locally on your device.", "Step 3: In an emergency, anyone with access to your device can open Nomadical and view your Medical ID instantly, without needing an internet connection."], screenshotLabel: "Screenshot: The Medical ID screen showing fields for blood type, allergies, medications, and emergency contacts filled in", screenshotHint: "Recommended: portrait, structured form layout with labeled fields and entered data visible", color: "#06b6d4" },
];

export default function FeatureDeepDive() {
  return (
    <section id="feature-details" className="py-24 bg-black relative overflow-hidden">
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/20 to-transparent" />

      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl font-black text-white mb-4">
            HOW IT ALL <span style={{ color: "#263e0f" }}>WORKS</span>
          </h2>
          <p className="text-white/60 text-lg max-w-2xl mx-auto">
            A detailed look at every feature in Nomadical
          </p>
        </motion.div>

        <div className="space-y-0">
          {features.map((feature, index) => {
            const isEven = index % 2 === 0;
            return (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6 }}
                className={`py-16 ${index > 0 ? "border-t border-white/10" : ""}`}
              >
                <div className={`grid lg:grid-cols-2 gap-12 items-start ${isEven ? "" : "direction-rtl"}`}>
                  {/* Text content */}
                  <div className={isEven ? "" : "lg:order-2"}>
                    <h3 className="text-2xl font-black text-white mb-6" style={{ borderLeft: `4px solid ${feature.color}`, paddingLeft: "16px" }}>
                      {feature.title}
                    </h3>

                    <div className="mb-6">
                      <h4 className="text-xs font-bold uppercase tracking-wider mb-2" style={{ color: feature.color }}>What It Does</h4>
                      <p className="text-white/70 text-sm leading-relaxed">{feature.description}</p>
                    </div>

                    <div className="mb-6">
                      <h4 className="text-xs font-bold uppercase tracking-wider mb-3" style={{ color: feature.color }}>How It Works</h4>
                      <ol className="space-y-2">
                        {feature.howItWorks.map((step: string, si: number) => (
                          <li key={si} className="flex items-start gap-3">
                            <span className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold text-white shrink-0 mt-0.5" style={{ backgroundColor: feature.color }}>
                              {si + 1}
                            </span>
                            <span className="text-white/70 text-sm">{step}</span>
                          </li>
                        ))}
                      </ol>
                    </div>

                    <div className="bg-white/5 border border-white/10 rounded-lg p-4">
                      <h4 className="text-xs font-bold uppercase tracking-wider mb-2" style={{ color: feature.color }}>Use Case</h4>
                      <p className="text-white/60 text-sm italic leading-relaxed">{feature.useCase}</p>
                    </div>
                  </div>

                  {/* Screenshot placeholder */}
                  <div className={isEven ? "" : "lg:order-1"}>
                    <ScreenshotSlot slot={`feature-${index}-deepdive`} label={feature.screenshotLabel} hint={feature.screenshotHint} />
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
